# this is for both server and client sides
Router.configure  
    layoutTemplate: 'layout'
    loadingTemplate: 'loading'

Router.onBeforeAction 'loading' # show loading template while waiting for the action

Router.map -> 
  @route 'home', path:'/'
  @route 'wlistTable'
  @route 'signup'
  @route 'qshareApplication'
  @route 'qshareApplicationSuccess'
  @route 'departmentpage'
  @route 'deforhos'
  @route 'deallhos'
  @route 'hosedde'
  @route 'albedde'
  @route 'applisuccess'
  @route 'specialistlist'
  @route 'allhospital'
  @route 'hosintro'
  @route 'hosedit'
  @route 'deedit'
  @route 'deadd'
  @route 'thescore'
  @route 'spintro'
  @route 'SpecialistMessageEdit'
  @route 'spadd'
  @route 'spintroedit'
  @route 'scorepage'
  @route 'thescoreofsp'
  @route 'departmentlist'
  @route 'dedataedit'
  @route 'allde'
  @route 'hosdataedit'
  @route 'deadd'
  @route 'home'
  @route 'SpecialistMessageEditforsp'
  @route 'spfirstpage'
  @route 'scoresuccess'
  @route 'spdataapplisuccess'
  @route 'hosallde'
  @route 'qshareIntroduction'
  @route 'vipintro'
  @route 'manage'
  @route 'messageBox'
  @route 'unreadMessage'
  @route 'undoneMessage'
  @route 'SpecialistLocalMessage'
  @route 'XiugaiHuiyuanQuanxian'
